/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderMenu: typeof import('./src/components/layouts/headerMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/views/HomePage/Home.vue')['default']
    Intro: typeof import('./src/components/views/HomePage/intro.vue')['default']
    Postlist: typeof import('./src/components/views/HomePage/postlist.vue')['default']
  }
}
